on: [push]

jobs:
  deploy_to_dev_job:
    runs-on: ubuntu-latest
    name: deploy to b4a dev environment
    steps:
      - name: checkout repository code
        id: checkout
        uses: actions/checkout@v3
      - name: deploy to DEV
        id: deploy-dev
        #uses: kopfan/b4a-action@v0.0.15
        uses: kopfan/back4app-deploy-action@v3
        with:
          appid: 'i0U3sduDSinluX2sHf1jRVi6pY7hhd8WZkUUAG88'
          project: 'CLI-Back4App'       
          accountKey: 'md1nNpoMS2yCOPx10oP1dUB1og7f5GUnliwS8Y44'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.deploy-dev.outputs.time }}"
